---
services:
    api:
        version: "0.0.1"
        network_mode: host
        volumes:
            - type: bind
              source: /var/log
              target: /var/jagerlog
        ports:
            client: "5000"
        base_url: "api/v1"
        admin:
            username: "admin"
            default_password: "admin"
        token:
            enabled: true
            secret: "jagereye_dev"
    database:
        version: "mongo-3.6.0"
        db_name: jagereye-dev
        network_mode: host
        ports:
            client: "27017"
    messaging:
        version: "nats-1.0.4"
        network_mode: host
        ports:
            client: "4222"
            monitor: "8222"
    obj_storage:
        version: "minio-RELEASE.2018-04-04T05-20-54Z"
        network_mode: host
        ports:
            client: "9000"
        volumes:
            data: /data:/data
        params:
            # The endpoint URL of object store.
            endpoint_url: 'http://localhost:9000'
            # The name of bucket to store objects.
            bucket_name: 'jager-store'
        credentials:
            access_key: 'jagereye'
            secret_key: 'jagereye'
    expiration:
        version: "0.0.1"
        network_mode: host
        params:
            # Expiration period in days.
            expiration_days: 30
            # The maximum allowance of event records.
            # The number "400,000" is for 1TB storage space, it assumes each event
            # contains about 2.2MB, including the database record, a 10-seconds video,
            # a thumbnail and a metadata json file.
            max_event_records: 400000
            # Repeat period of expiration function (in minutes).
            repeat_period_mins: 10
apps:
    intrusion_detection:
        version: "0.0.1"
        network_mode: host
logging:
    loglevel: "debug"
    transports:
        stdout:
            default_enabled: true
        syslog:
            default_enabled: true
            host: &syslog_server_host "localhost"
            port: &syslog_server_port 514
            facility: 'local1'
            protocol: 'udp4'
