---
services:
    api:
        version: "0.0.1"
        network_mode: host
        ports:
            client: "5000"
    database:
        version: "mongo-3.6.0"
        db_name: jagereye-dev
        network_mode: host
        ports:
            client: "27017"
    messaging:
        version: "nats-1.0.4"
        network_mode: host
        ports:
            client: "4222"
            monitor: "8222"
    mem_db:
        version: "redis-4.0.6"
        network_mode: host
        ports:
            client: "6379"
    res_mgr:
        version: "0.0.1"
        network_mode: host
        volumes:
            docker_sock: /var/run/docker.sock:/var/run/docker.sock
        worker:
            network_mode: host
    obj_storage:
        version: "minio-RELEASE.2018-04-04T05-20-54Z"
        network_mode: host
        ports:
            client: "9000"
        volumes:
            data: /data:/data
        params:
            # The endpoint URL of object store.
            endpoint_url: 'http://localhost:9000'
            # The name of bucket to store objects.
            bucket_name: 'jager-store'
        credentials:
            access_key: 'jagereye'
            secret_key: 'jagereye'
apps:
    tripwire:
        version: "0.0.1"
        network_mode: host
